packages:
  - "apps/*"
  - "packages/*"
  # Exclusions (pnpm will ignore these when scanning)
  - "!**/dist/**"
  - "!**/build/**"
  - "!**/.next/**"
  - "!**/.turbo/**"
  - "!**/.vite/**"
  - "!**/node_modules/**"
